name: Test custom gha action
run-name: gha action first

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Show Current Time
        run: echo "Current time"
      - uses: gha_javascript_action1@main
    

    
